// Generated by https://quicktype.io

export interface ZZinterfaceServices {
// Generated by https://quicktype.io

    numPages : number;
    numLang : number

}

export interface interfaceBudget {

  web        : number,
  seo        : number,
  ads        : number,

  pages      : number,
  languages  : number,

  total?     : number

}
